pipeline:

  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-athena-maintenance
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    context: app
    dockerfile: app/Dockerfile
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
    when:
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-apps-notprod
      - INSECURE_SKIP_TLS_VERIFY=true
      - KUBE_SCHEDULE="45 12 * * *"
    commands:
      - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
      - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
      - export ATHENA_LOG=$$NOTPROD_ATHENA_LOG
      - export CSV_S3_BUCKET=$$NOTPROD_CSV_S3_BUCKET
      - export CSV_S3_FILE=$$NOTPROD_CSV_S3_FILE
      - export AWS_ACCESS_KEY_ID=$$NOTPROD_AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$$NOTPROD_AWS_SECRET_ACCESS_KEY
      - export AWS_DEFAULT_REGION=$$NOTPROD_AWS_DEFAULT_REGION
      - kd -f kube/secret.yml
      - kd --replace -f kube/cronjob.yml
    secrets:
      - NOTPROD_KUBE_TOKEN
      - NOTPROD_KUBE_SERVER
      - NOTPROD_ATHENA_LOG
      - NOTPROD_CSV_S3_BUCKET
      - NOTPROD_CSV_S3_FILE
      - NOTPROD_AWS_ACCESS_KEY_ID
      - NOTPROD_AWS_SECRET_ACCESS_KEY
      - NOTPROD_AWS_DEFAULT_REGION
    when:
      event: push

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-apps
      - INSECURE_SKIP_TLS_VERIFY=true
      - KUBE_SCHEDULE="0 */12 * * *"
    commands:
      - export KUBE_TOKEN=$$PROD_KUBE_TOKEN
      - export KUBE_SERVER=$$PROD_KUBE_SERVER
      - export ATHENA_LOG=$$PROD_ATHENA_LOG
      - export CSV_S3_BUCKET=$$PROD_CSV_S3_BUCKET
      - export CSV_S3_FILE=$$PROD_CSV_S3_FILE
      - export AWS_ACCESS_KEY_ID=$$PROD_AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$$PROD_AWS_SECRET_ACCESS_KEY
      - export AWS_DEFAULT_REGION=$$PROD_AWS_DEFAULT_REGION
      - kd -f kube/secret.yml
      - kd --replace -f kube/cronjob.yml
    secrets:
      - PROD_KUBE_TOKEN
      - PROD_KUBE_SERVER
      - PROD_ATHENA_LOG
      - PROD_CSV_S3_BUCKET
      - PROD_CSV_S3_FILE
      - PROD_AWS_ACCESS_KEY_ID
      - PROD_AWS_SECRET_ACCESS_KEY
      - PROD_AWS_DEFAULT_REGION
    when:
      environment: production
      event: deployment
