---
global-variables:
  vault-image: &vault-image docker.digital.homeoffice.gov.uk/dq/dq-vault-awscli:1.37
  trivy-image: &trivy-image quay.io/ukhomeofficedigital/trivyscanner:master

kind: pipeline
name: matrix-1
type: kubernetes

platform:
  os: linux
  arch: amd64

x-anchors:
  rotate-app-user-aws-key: &rotate-app-user-aws-key
      # Retrive vault secrets
    - vault read aws_dacc_dq/creds/drone > aws_creds.json
    - export LEASE_ID=$(cat aws_creds.json | grep lease_id | awk -F ' ' '{print $2}')
    # Update the token TTL to 10mins
    - vault lease renew -increment=600 $${LEASE_ID}
    # Get the AWS credentials
    - export AWS_ACCESS_KEY_ID=$(cat aws_creds.json | grep access_key | awk -F ' ' '{print $2}')
    - export AWS_SECRET_ACCESS_KEY=$(cat aws_creds.json | grep secret_key | awk -F ' ' '{print $2}')
    - export AWS_DEFAULT_REGION=eu-west-2
    # Since AWS is eventually consistent we need to sleep a little while so the AWS key is created and made available
    - sleep 10
    # get app key id from ssm
    - export OLD_AWS_ACCESS_KEY_ID=$(aws ssm get-parameters --name $SSM_KEY_ID --query "Parameters[*].{Value:Value}" --with-decryption | grep Value | awk -F ' ' '{print $2}' | tr -d '"')
    # generate new key & id for app user
    - aws iam create-access-key --user-name $APP_USER_NAME > new-key.json
    - export NEW_AWS_ACCESS_KEY_ID=$(cat new-key.json | grep AccessKeyId | awk -F ' ' '{print $2}' | tr -d '"' | tr -d ',')
    - export NEW_AWS_SECRET_ACCESS_KEY=$(cat new-key.json | grep SecretAccessKey | awk -F ' ' '{print $2}' | tr -d '"' | tr -d ',')
    # delete old iam key &id
    - aws iam delete-access-key --access-key-id $OLD_AWS_ACCESS_KEY_ID --user-name $APP_USER_NAME
    # push new key & id to SSM
    - aws ssm put-parameter --name $SSM_KEY_ID --type "SecureString" --value $NEW_AWS_ACCESS_KEY_ID --overwrite
    - aws ssm put-parameter --name $SSM_SECURE_KEY --type "SecureString" --value $NEW_AWS_SECRET_ACCESS_KEY --overwrite
    # encode new key and id
    - echo "NEW_AWS_ACCESS_KEY_ID=$(echo -n $NEW_AWS_ACCESS_KEY_ID | base64)" > new_iam_secret.sh
    - echo "NEW_AWS_SECRET_ACCESS_KEY=$(echo -n $NEW_AWS_SECRET_ACCESS_KEY | base64)" >> new_iam_secret.sh
    - sleep 10

steps:
- name: build_and_push_image
  pull: if-not-exists
  image: plugins/docker
  settings:
    build_args:
    - PYTHON_ALPINE_VERSION=b16
    context: app
    dockerfile: app/Dockerfile
    force_tag: true
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/dq-athena-maintenance
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}
    - b${DRONE_BUILD_NUMBER}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    event:
    - push

- name: trivy_scan
  pull: if-not-exists
  image: *trivy-image
  commands:
  - trivy image --ignore-unfixed --exit-code 0 --no-progress quay.io/ukhomeofficedigital/dq-athena-maintenance:${DRONE_COMMIT_SHA}
  when:
    branch:
      exclude:
      - master
    event:
    - push

- name: rotate_aws_keys_np
  pull: if-not-exists
  image: *vault-image
  commands:
    *rotate-app-user-aws-key
  environment:
    SSM_KEY_ID: kubernetes-athena-maintenance-user-id-apps-notprod-dq
    SSM_SECURE_KEY: kubernetes-athena-maintenance-user-key-apps-notprod-dq
    APP_USER_NAME:  iam-user-athena-maintenance-apps-notprod-dq
    ENV: notprod
    VAULT_ADDR:
      from_secret: VAULT_ADDR_NOTPROD
    VAULT_TOKEN:
      from_secret: VAULT_TOKEN_NOTPROD
  when:
    event:
      - push

- name: deploy_to_dev
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - source new_iam_secret.sh
  - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
  - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
  - export ATHENA_LOG=$$NOTPROD_ATHENA_LOG
  - export CSV_S3_BUCKET=$$NOTPROD_CSV_S3_BUCKET
  - export CSV_S3_FILE=$$NOTPROD_CSV_S3_FILE
  - export AWS_ACCESS_KEY_ID=$$NEW_AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$$NEW_AWS_SECRET_ACCESS_KEY
  - export AWS_DEFAULT_REGION=$$NOTPROD_AWS_DEFAULT_REGION
  - kd -f kube/secret.yml
  - kd --replace -f kube/cronjob.yml
  environment:
    INSECURE_SKIP_TLS_VERIFY: true
    KUBE_NAMESPACE: dq-apps-notprod
    KUBE_SCHEDULE: "\"0 */12 * * *\""
    NOTPROD_ATHENA_LOG:
      from_secret: NOTPROD_ATHENA_LOG
    NOTPROD_AWS_DEFAULT_REGION:
      from_secret: NOTPROD_AWS_DEFAULT_REGION
    NOTPROD_CSV_S3_BUCKET:
      from_secret: NOTPROD_CSV_S3_BUCKET
    NOTPROD_CSV_S3_FILE:
      from_secret: NOTPROD_CSV_S3_FILE
    NOTPROD_KUBE_SERVER:
      from_secret: NOTPROD_KUBE_SERVER
    NOTPROD_KUBE_TOKEN:
      from_secret: NOTPROD_KUBE_TOKEN
  when:
    event:
    - push

- name: rotate_aws_keys_prod
  pull: if-not-exists
  image: *vault-image
  commands:
    *rotate-app-user-aws-key
  environment:
    SSM_KEY_ID: kubernetes-athena-maintenance-user-id-apps-prod-dq
    SSM_SECURE_KEY: kubernetes-athena-maintenance-user-key-apps-prod-dq
    APP_USER_NAME: iam-user-athena-maintenance-apps-prod-dq
    ENV: prod
    VAULT_ADDR:
      from_secret: VAULT_ADDR_PROD
    VAULT_TOKEN:
      from_secret: VAULT_TOKEN_PROD
  when:
    branch:
    - master
    event:
    - promote
    target:
    - production

- name: deploy_to_prod
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - source new_iam_secret.sh
  - export KUBE_TOKEN=$$PROD_KUBE_TOKEN
  - export KUBE_SERVER=$$PROD_KUBE_SERVER
  - export ATHENA_LOG=$$PROD_ATHENA_LOG
  - export CSV_S3_BUCKET=$$PROD_CSV_S3_BUCKET
  - export CSV_S3_FILE=$$PROD_CSV_S3_FILE
  - export AWS_ACCESS_KEY_ID=$$NEW_AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$$NEW_AWS_SECRET_ACCESS_KEY
  - export AWS_DEFAULT_REGION=$$PROD_AWS_DEFAULT_REGION
  - kd -f kube/secret.yml
  - kd --replace -f kube/cronjob.yml
  environment:
    INSECURE_SKIP_TLS_VERIFY: true
    KUBE_NAMESPACE: dq-apps
    KUBE_SCHEDULE: "\"0 */12 * * *\""
    PROD_ATHENA_LOG:
      from_secret: PROD_ATHENA_LOG
    PROD_AWS_DEFAULT_REGION:
      from_secret: PROD_AWS_DEFAULT_REGION
    PROD_CSV_S3_BUCKET:
      from_secret: PROD_CSV_S3_BUCKET
    PROD_CSV_S3_FILE:
      from_secret: PROD_CSV_S3_FILE
    PROD_KUBE_SERVER:
      from_secret: PROD_KUBE_SERVER
    PROD_KUBE_TOKEN:
      from_secret: PROD_KUBE_TOKEN
  when:
    branch:
    - master
    event:
    - promote
    target:
    - production

- name: renew-vault-tokens
  pull: if-not-exists
  image: *vault-image
  commands:
    # Renew NotProd Drone Vault Token
    - export VAULT_TOKEN=$${VAULT_TOKEN_NOTPROD}
    - export VAULT_ADDR=$${VAULT_ADDR_NOTPROD}
    - vault token renew > /dev/null
    # Renew Prod Drone Vault Token
    - export VAULT_TOKEN=$${VAULT_TOKEN_PROD}
    - export VAULT_ADDR=$${VAULT_ADDR_PROD}
    - vault token renew > /dev/null
  environment:
    VAULT_ADDR_NOTPROD:
      from_secret: VAULT_ADDR_NOTPROD
    VAULT_TOKEN_NOTPROD:
      from_secret: VAULT_TOKEN_NOTPROD
    VAULT_ADDR_PROD:
      from_secret: VAULT_ADDR_PROD
    VAULT_TOKEN_PROD:
      from_secret: VAULT_TOKEN_PROD
  when:
    event:
      - cron
    cron:
      - renew-vault-tokens    

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
