---
apiVersion: v1
kind: Secret
metadata:
  name: dq-athena-partition-maintenance
type: Opaque
data:
  ATHENA_LOG: {{.ATHENA_LOG}}
  CSV_S3_BUCKET: {{.CSV_S3_BUCKET}}
  CSV_S3_FILE: {{.CSV_S3_FILE}}
  AWS_ACCESS_KEY_ID: {{.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: {{.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: {{.AWS_DEFAULT_REGION}}
